version: '3.7'
services:
    database:
        image: 'mariadb:10.7.1'
        container_name: mysql
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: leBonCoin
        ports:
            # To allow the host machine to access the ports below, modify the lines below.
            # For example, to allow the host to connect to port 3306 on the container, you would change
            # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
            # See https://docs.docker.com/compose/compose-file/#ports for more information.
            - '3306'

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        ports:
            - 3080:80
        environment:
            PMA_HOST: database
            PMA_ARBITRARY: 1
        restart: always
        links:
            - database